### ISSUE TITLE
change ebucore:FileSize to ebucore:fileSize

### ISSUE THREAD

**Issue by afred** [WGBH/pbucore#28]
incorrect output can be seen [here](https://github.com/WGBH/pbucore/blob/master/rdf_xml/instantiationFileSize_rdf.xml#L32)

**done when**
- xsl stylesheet it updated to produce correct ebucore tag
- the rdf output file we're using for testing is updated.

**Comment by jlhardes** [comment]
This is fixed in master with commit: c83e887300685f15e6104560640be2eebbac4ade
